# Generated by Django 2.2.1 on 2019-06-02 09:26

from django.db import migrations, models
import dutch_broomstick.models


class Migration(migrations.Migration):

    dependencies = [
        ('dutch_broomstick', '0005_remove_room_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='url',
            field=models.CharField(default=dutch_broomstick.models.random_url, max_length=10, unique=True),
        ),
    ]
