# Generated by Django 2.2.1 on 2019-06-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dutch_broomstick', '0006_room_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('layername', models.CharField(blank=True, max_length=30)),
                ('currency', models.CharField(blank=True, max_length=30)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutch_broomstick.Room')),
            ],
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='membername',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('forWhat', models.CharField(max_length=30)),
                ('fromWho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutch_broomstick.Member')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutch_broomstick.Layer')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutch_broomstick.Payment')),
                ('toWho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutch_broomstick.Member')),
            ],
        ),
    ]
